version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    hostname: $MYSQL_HOST
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER

  php-apache:
    build: .
    # .envから環境変数を取得
    env_file: .env
    volumes:
      - ./app:/var/www/html
    ports:
      - "30:80"

volumes:
  db_data: {}