version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
        region: ${AWS_REGION}
        account-url: ${AWS_ECR_ACCOUNT_URL}
        repo: 'dbc'
        tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
        requires:
          - aws-ecr/build_and_push_image
        family: 'dbc-task'
        cluster-name: 'dbc-container'
        service-name: 'dbc'
        container-image-name-updates: 'container=dbc-container,tag=${CIRCLE_SHA1}'