version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: 'AWS_ECR_ACCOUNT_URL'
          repo: 'dbc'
          region: 'AWS_REGION'
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: 'dbc-tas'
          cluster-name: 'dbc-clu'
          service-name: 'dbc'
          container-image-name-updates: 'container=app,tag=${CIRCLE_SHA1}'