version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          name: 'AWS_ECR_ACCOUNT_URL'
          account-url: 'AWS_ECR_ACCOUNT_URL'
          repo: 'dbc'
          region: 'AWS_REGION'
          # tag: "${CIRCLE_SHA1}"
      - aws-ecr/build_and_push_image:
          name: 'AWS_ECR_ACCOUNT_URL2'
          account-url: 'AWS_ECR_ACCOUNT_URL2'
          repo: 'dbc'
          region: 'AWS_REGION'
          # tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - 'AWS_ECR_ACCOUNT_URL'
            - 'AWS_ECR_ACCOUNT_URL2'
          family: 'dbc-task'
          cluster-name: 'dbc-cluster'
          service-name: 'dbc'
          container-image-name-updates: 'container=appp,tag=${CIRCLE_SHA1}'
