version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  aws-ecs: circleci/aws-ecs@0.0.3
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: '${AWS_ECR_ACCOUNT_URL}'
          repo: 'dbc'
          region: '${AWS_REGION}'
          tag: '${CIRCLE_SHA1}
  '
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: 'dd79c1f9-4c2e-4134-86e2-6acb16467c85'
          cluster-name: 'dbc-cluster'
          container-image-name-updates: 'container=dbc-container,tag=${CIRCLE_SHA1}'